plugins {
    id 'application'
    id 'java'
}

group = 'com.example.a'
version = '0.1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
}

repositories {
    mavenCentral()
}

application {
    mainClass = 'com.example.a.App'
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}

test {
    useJUnit()
}
